"""
csv_to_agent.py
Automated script to ingest a CSV, train an ensemble model, and generate an MCP-ready Agent class.
"""

import json
import argparse
import pandas as pd
from pathlib import Path
from typing import Any

# Import from your factory file
from services.ml_mcp_server.models._agent_factory import AgentConfig, create_ml_agent, DynamicMLAgent


def generate_agent_class_file(
    output_py_path: str | Path,
    class_name: str,
    agent_name: str,
    artifact_filename: str,
    feature_names: list[str],
    target_classes: list[str],
    sample_data_dict: dict[str, float],
    csv_filename: str
):
    """Generates the drop-in Python wrapper class for the MCP server."""
    
    formatted_sample = json.dumps(sample_data_dict, indent=8).replace('}', '        }')
    config_var_name = f"_{class_name.upper()}_CONFIG"
    
    python_code = f'''"""Autogenerated ML Agent wrapper for {class_name}.

This file was generated by the CSV Builder Script from {csv_filename}.
"""

from pathlib import Path
from typing import Any

from services.ml_mcp_server.models._agent_factory import AgentConfig, DynamicMLAgent

# --- 1. Paths & Configuration ---
_ARTIFACT_PATH = Path(__file__).parent.parent / "artifacts" / "{artifact_filename}"

{config_var_name} = AgentConfig(
    agent_name="{agent_name}",
    description="Automated ensemble classifier generated from local data ({csv_filename}).",
    version="1.0.0-auto",
    artifact_path=_ARTIFACT_PATH,
    feature_names={feature_names},
    target_classes={target_classes},
    trained_on_desc="Local Data via Automated Builder",
    n_splits=5
)

# --- 2. MCP Server Agent Class ---
class {class_name}(DynamicMLAgent):
    """Dynamic binary classifier for {agent_name}."""

    def __init__(self) -> None:
        super().__init__({config_var_name})

    def sample_inputs(self) -> dict[str, Any]:
        """A representative sample case extracted during the build process."""
        return {formatted_sample}
'''

    output_py_path = Path(output_py_path)
    output_py_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_py_path, "w") as f:
        f.write(python_code)
        
    print(f"[Code Generator] Successfully wrote server class to: {output_py_path}")


def ingest_csv_and_build_agent(
    csv_path: str | Path,
    target_column: str,
    agent_name: str,
    new_feature_names: list[str] = None
) -> DynamicMLAgent:
    
    csv_path = Path(csv_path)
    print(f"\n--- Starting Agent Build Process for: {agent_name} ---")
    
    if not csv_path.exists():
        raise FileNotFoundError(f"Could not find CSV at {csv_path}")
    
    df = pd.read_csv(csv_path)
    
    if target_column not in df.columns:
        raise ValueError(f"Target column '{target_column}' not found. Available: {df.columns.tolist()}")
        
    # 1. Define the Package Root (where this script lives)
    PACKAGE_ROOT = Path(__file__).parent.absolute()
    PACKAGE_ROOT_ROOT = Path(__file__).parent.parent.absolute()
    
    # 2. Define Output Paths relative to the package root
    artifact_filename = f"{agent_name}_xgb_dynamic.joblib"
    
    # This creates a folder named 'artifacts' inside your package
    artifact_dir = PACKAGE_ROOT_ROOT / "artifacts"
    artifact_path = artifact_dir / artifact_filename

    # 1. Handle Missing Values in Target
    df = df.dropna(subset=[target_column])
    
    # 2. Split Features and Target
    y_series = df[target_column]
    X_df = df.drop(columns=[target_column])
    
    # 3. Apply Custom Feature Names (if provided)
    if new_feature_names:
        original_features = X_df.columns.tolist()
        if len(new_feature_names) != len(original_features):
            # Print the detailed mismatch report to standard out
            print("\n[ERROR] FEATURE RENAME MISMATCH!")
            print(f"Original features ({len(original_features)}): {original_features}")
            print(f"Provided features ({len(new_feature_names)}): {new_feature_names}")
            print(f"Mismatch: You provided {len(new_feature_names)} names, but the CSV requires exactly {len(original_features)} names.")
            
            # Raise the exception to halt execution
            raise ValueError(f"Feature count mismatch: Expected {len(original_features)}, got {len(new_feature_names)}.")
        
        print("[Info] Successfully mapped new feature names.")
        X_df.columns = new_feature_names
    
    # 4. Automatic Categorical Feature Encoding & Imputation
    X_df = pd.get_dummies(X_df, drop_first=True, dtype=float)
    X_df = X_df.fillna(X_df.median(numeric_only=True))
    feature_names = X_df.columns.tolist()
    
    # 5. Target Class Mapping
    unique_classes = sorted(y_series.unique().tolist())
    if len(unique_classes) > 2:
        raise ValueError(f"Target has >2 classes {unique_classes}. Only binary classification is supported.")
    
    target_mapping = {unique_classes[0]: 0, unique_classes[1]: 1}
    y_series = y_series.map(target_mapping)
    target_class_names = [str(unique_classes[0]), str(unique_classes[1])]

    # 7. Generate Configuration
    config = AgentConfig(
        agent_name=agent_name,
        description=f"Automated classifier built from {csv_path.name}.",
        version="1.0.0-auto",
        artifact_path=artifact_path,
        feature_names=feature_names,
        target_classes=target_class_names,
        trained_on_desc=f"Local CSV: {csv_path.name} (n={len(df)})",
        n_splits=5
    )

    # 8. Train the Agent
    print(f"Configuring agent with {len(feature_names)} features...")
    agent = create_ml_agent(config)
    agent.train(X_df, y_series)
    
    # 9. Verification & Schema Sample Extraction
    sample_data = {
        agent._sanitize(k): float(v) 
        for k, v in zip(feature_names, X_df.iloc[0].values)
    }
    
    # 10. Generate the Python Agent Wrapper
    class_name = "".join(word.capitalize() for word in agent_name.split("_")) + "Agent"
    output_py_path = PACKAGE_ROOT / f"{agent_name}_xgb.py"
    
    generate_agent_class_file(
        output_py_path=output_py_path,
        class_name=class_name,
        agent_name=agent_name,
        artifact_filename=artifact_filename,
        feature_names=feature_names,
        target_classes=target_class_names,
        sample_data_dict=sample_data,
        csv_filename=csv_path.name
    )

    return agent


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert a CSV into a trained ML Agent .py file")
    parser.add_argument("--csv_path", type=str, help="Path to the input CSV file")
    parser.add_argument("--target_column", type=str, help="The name of the column to predict")
    parser.add_argument("--agent_name", type=str, help="System name for the agent (e.g., 'employee_churn')")
    
    # Added argument for overriding feature names
    parser.add_argument(
        "--new-feature-names", 
        type=str, 
        nargs="+", 
        default=None,
        help="Optional: Space-separated list of new feature names. Must exactly match the number of feature columns."
    )
    
    args = parser.parse_args()
    
    ingest_csv_and_build_agent(
        csv_path=args.csv_path, 
        target_column=args.target_column, 
        agent_name=args.agent_name,
        new_feature_names=args.new_feature_names
    )