"""Autogenerated ML Agent wrapper for DengueAgent.

This file was generated by the CSV Builder Script from dengue_diseases_dataset.csv.
"""

from pathlib import Path
from typing import Any

from services.ml_mcp_server.models._agent_factory import AgentConfig, DynamicMLAgent

# --- 1. Paths & Configuration ---
_ARTIFACT_PATH = Path(__file__).parent.parent / "artifacts" / "dengue_xgb_dynamic.joblib"

_DENGUEAGENT_CONFIG = AgentConfig(
    agent_name="dengue",
    description="Automated ensemble classifier generated from local data (dengue_diseases_dataset.csv).",
    version="1.0.0-auto",
    artifact_path=_ARTIFACT_PATH,
    feature_names=['age', 'hemoglobin', 'wbc_count', 'differential_count', 'rbc_count', 'platelet_count', 'pdw', 'gender_Female', 'gender_Male'],
    target_classes=['0.0', '1.0'],
    trained_on_desc="Local Data via Automated Builder",
    n_splits=5
)

# --- 2. MCP Server Agent Class ---
class DengueAgent(DynamicMLAgent):
    """Dynamic binary classifier for dengue."""

    def __init__(self) -> None:
        super().__init__(_DENGUEAGENT_CONFIG)

    def sample_inputs(self) -> dict[str, Any]:
        """A representative sample case extracted during the build process."""
        return {
        "age": 43.0,
        "hemoglobin": 12.6,
        "wbc_count": 2200.0,
        "differential_count": 1.0,
        "rbc_count": 1.0,
        "platelet_count": 62000.0,
        "pdw": 11.0,
        "gender_Female": 0.0,
        "gender_Male": 1.0
        }
