"""Autogenerated ML Agent wrapper for HeartFailureAgent.

This file was generated by the CSV Builder Script from heart_failure_clinical_records_dataset.csv.
"""

from pathlib import Path
from typing import Any

from services.ml_mcp_server.models._agent_factory import AgentConfig, DynamicMLAgent

# --- 1. Paths & Configuration ---
_ARTIFACT_PATH = Path(__file__).parent.parent / "artifacts" / "heart_failure_xgb_dynamic.joblib"

_HEARTFAILUREAGENT_CONFIG = AgentConfig(
    agent_name="heart_failure",
    description="Automated ensemble classifier generated from local data (heart_failure_clinical_records_dataset.csv).",
    version="1.0.0-auto",
    artifact_path=_ARTIFACT_PATH,
    feature_names=['age', 'anaemia', 'creatinine_phosphokinase', 'diabetes', 'ejection_fraction', 'high_blood_pressure', 'platelet_count', 'creatinine', 'sodium', 'gender', 'smoking', 'time'],
    target_classes=['0', '1'],
    trained_on_desc="Local Data via Automated Builder",
    n_splits=5
)

# --- 2. MCP Server Agent Class ---
class HeartFailureAgent(DynamicMLAgent):
    """Dynamic binary classifier for heart_failure."""

    def __init__(self) -> None:
        super().__init__(_HEARTFAILUREAGENT_CONFIG)

    def sample_inputs(self) -> dict[str, Any]:
        """A representative sample case extracted during the build process."""
        return {
        "age": 75.0,
        "anaemia": 0.0,
        "creatinine_phosphokinase": 582.0,
        "diabetes": 0.0,
        "ejection_fraction": 20.0,
        "high_blood_pressure": 1.0,
        "platelet_count": 265000.0,
        "creatinine": 1.9,
        "sodium": 130.0,
        "gender": 1.0,
        "smoking": 0.0,
        "time": 4.0
        }
