"""Autogenerated ML Agent wrapper for HeartDiseaseAgent.

This file was generated by the CSV Builder Script from heart.csv.
"""

from pathlib import Path
from typing import Any

from services.ml_mcp_server.models._agent_factory import AgentConfig, DynamicMLAgent

# --- 1. Paths & Configuration ---
_ARTIFACT_PATH = Path(__file__).parent.parent / "artifacts" / "heart_disease_xgb_dynamic.joblib"

_HEARTDISEASEAGENT_CONFIG = AgentConfig(
    agent_name="heart_disease",
    description="Automated ensemble classifier generated from local data (heart.csv).",
    version="1.0.0-auto",
    artifact_path=_ARTIFACT_PATH,
    feature_names=['age', 'gender', 'cp', 'trestbps', 'cholesterol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal'],
    target_classes=['0', '1'],
    trained_on_desc="Local Data via Automated Builder",
    n_splits=5
)

# --- 2. MCP Server Agent Class ---
class HeartDiseaseAgent(DynamicMLAgent):
    """Dynamic binary classifier for heart_disease."""

    def __init__(self) -> None:
        super().__init__(_HEARTDISEASEAGENT_CONFIG)

    def sample_inputs(self) -> dict[str, Any]:
        """A representative sample case extracted during the build process."""
        return {
        "age": 52.0,
        "gender": 1.0,
        "cp": 0.0,
        "trestbps": 125.0,
        "cholesterol": 212.0,
        "fbs": 0.0,
        "restecg": 1.0,
        "thalach": 168.0,
        "exang": 0.0,
        "oldpeak": 1.0,
        "slope": 2.0,
        "ca": 2.0,
        "thal": 3.0
        }
