"""Autogenerated ML Agent wrapper for LiverDiseaseAgent.

This file was generated by the CSV Builder Script from indian_liver_patient_dataset_ilpd.csv.
"""

from pathlib import Path
from typing import Any

from services.ml_mcp_server.models._agent_factory import AgentConfig, DynamicMLAgent

# --- 1. Paths & Configuration ---
_ARTIFACT_PATH = Path(__file__).parent.parent / "artifacts" / "liver_disease_xgb_dynamic.joblib"

_LIVERDISEASEAGENT_CONFIG = AgentConfig(
    agent_name="liver_disease",
    description="Automated ensemble classifier generated from local data (indian_liver_patient_dataset_ilpd.csv).",
    version="1.0.0-auto",
    artifact_path=_ARTIFACT_PATH,
    feature_names=['age', 'total_bilirubin', 'direct_bilirubin', 'alkaline_phosphotase', 'alamine_aminotransferase', 'aspartate_aminotransferase', 'total_protiens', 'albumin', 'albumin_and_globulin_ratio', 'gender_Male'],
    target_classes=['1', '2'],
    trained_on_desc="Local Data via Automated Builder",
    n_splits=5
)

# --- 2. MCP Server Agent Class ---
class LiverDiseaseAgent(DynamicMLAgent):
    """Dynamic binary classifier for liver_disease."""

    def __init__(self) -> None:
        super().__init__(_LIVERDISEASEAGENT_CONFIG)

    def sample_inputs(self) -> dict[str, Any]:
        """A representative sample case extracted during the build process."""
        return {
        "age": 65.0,
        "total_bilirubin": 0.7,
        "direct_bilirubin": 0.1,
        "alkaline_phosphotase": 187.0,
        "alamine_aminotransferase": 16.0,
        "aspartate_aminotransferase": 18.0,
        "total_protiens": 6.8,
        "albumin": 3.3,
        "albumin_and_globulin_ratio": 0.9,
        "gender_Male": 0.0
        }
