"""Autogenerated ML Agent wrapper for SepsisAgent.

This file was generated by the CSV Builder Script from dataset.csv.
"""

from pathlib import Path
from typing import Any

from services.ml_mcp_server.models._agent_factory import AgentConfig, DynamicMLAgent

# --- 1. Paths & Configuration ---
_ARTIFACT_PATH = Path(__file__).parent.parent / "artifacts" / "sepsis_xgb_dynamic.joblib"

_SEPSISAGENT_CONFIG = AgentConfig(
    agent_name="sepsis",
    description="Automated ensemble classifier generated from local data (dataset.csv).",
    version="1.0.0-auto",
    artifact_path=_ARTIFACT_PATH,
    feature_names=['Unnamed: 0', 'hour', 'heart_rate', 'oxygen_saturation', 'body_temperature', 'systolic_bp', 'map', 'diastolic_bp', 'respiratory_rate', 'etco2', 'baseexcess', 'hco3', 'fio2', 'ph', 'paco2', 'oxygen_saturation.1', 'ast', 'bun', 'alkalinephos', 'calcium', 'chloride', 'creatinine', 'bilirubin_direct', 'glucose', 'lactate', 'magnesium', 'phosphate', 'potassium', 'bilirubin_total', 'troponini', 'hct', 'hemoglobin', 'ptt', 'wbc_count', 'fibrinogen', 'platelet_count', 'age', 'gender', 'unit1', 'unit2', 'hospadmtime', 'iculos', 'patient_id'],
    target_classes=['0', '1'],
    trained_on_desc="Local Data via Automated Builder",
    n_splits=5
)

# --- 2. MCP Server Agent Class ---
class SepsisAgent(DynamicMLAgent):
    """Dynamic binary classifier for sepsis."""

    def __init__(self) -> None:
        super().__init__(_SEPSISAGENT_CONFIG)

    def sample_inputs(self) -> dict[str, Any]:
        """A representative sample case extracted during the build process."""
        return {
        "Unnamed:_0": 0.0,
        "hour": 0.0,
        "heart_rate": 83.5,
        "oxygen_saturation": 98.0,
        "body_temperature": 37.0,
        "systolic_bp": 121.0,
        "map": 80.0,
        "diastolic_bp": 62.0,
        "respiratory_rate": 18.0,
        "etco2": 33.0,
        "baseexcess": 0.0,
        "hco3": 24.0,
        "fio2": 0.5,
        "ph": 7.38,
        "paco2": 40.0,
        "oxygen_saturation.1": 97.0,
        "ast": 41.0,
        "bun": 17.0,
        "alkalinephos": 74.0,
        "calcium": 8.3,
        "chloride": 106.0,
        "creatinine": 0.94,
        "bilirubin_direct": 0.445,
        "glucose": 127.0,
        "lactate": 1.8,
        "magnesium": 2.0,
        "phosphate": 3.3,
        "potassium": 4.1,
        "bilirubin_total": 0.9,
        "troponini": 0.3,
        "hct": 30.3,
        "hemoglobin": 10.3,
        "ptt": 32.4,
        "wbc_count": 10.3,
        "fibrinogen": 250.0,
        "platelet_count": 181.0,
        "age": 68.54,
        "gender": 0.0,
        "unit1": 0.0,
        "unit2": 1.0,
        "hospadmtime": -0.02,
        "iculos": 1.0,
        "patient_id": 17072.0
        }
