"""Autogenerated ML Agent wrapper for StrokeAgent.

This file was generated by the CSV Builder Script from healthcare_dataset_stroke_data.csv.
"""

from pathlib import Path
from typing import Any

from services.ml_mcp_server.models._agent_factory import AgentConfig, DynamicMLAgent

# --- 1. Paths & Configuration ---
_ARTIFACT_PATH = Path(__file__).parent.parent / "artifacts" / "stroke_xgb_dynamic.joblib"

_STROKEAGENT_CONFIG = AgentConfig(
    agent_name="stroke",
    description="Automated ensemble classifier generated from local data (healthcare_dataset_stroke_data.csv).",
    version="1.0.0-auto",
    artifact_path=_ARTIFACT_PATH,
    feature_names=['patient_id', 'age', 'hypertension', 'heart_disease', 'glucose', 'bmi', 'gender_Male', 'gender_Other', 'ever_married_Yes', 'work_type_Never_worked', 'work_type_Private', 'work_type_Self-employed', 'work_type_children', 'residence_type_Urban', 'smoking_status_formerly smoked', 'smoking_status_never smoked', 'smoking_status_smokes'],
    target_classes=['0', '1'],
    trained_on_desc="Local Data via Automated Builder",
    n_splits=5
)

# --- 2. MCP Server Agent Class ---
class StrokeAgent(DynamicMLAgent):
    """Dynamic binary classifier for stroke."""

    def __init__(self) -> None:
        super().__init__(_STROKEAGENT_CONFIG)

    def sample_inputs(self) -> dict[str, Any]:
        """A representative sample case extracted during the build process."""
        return {
        "patient_id": 9046.0,
        "age": 67.0,
        "hypertension": 0.0,
        "heart_disease": 1.0,
        "glucose": 228.69,
        "bmi": 36.6,
        "gender_Male": 1.0,
        "gender_Other": 0.0,
        "ever_married_Yes": 1.0,
        "work_type_Never_worked": 0.0,
        "work_type_Private": 1.0,
        "work_type_Self-employed": 0.0,
        "work_type_children": 0.0,
        "residence_type_Urban": 1.0,
        "smoking_status_formerly_smoked": 1.0,
        "smoking_status_never_smoked": 0.0,
        "smoking_status_smokes": 0.0
        }
