"""Autogenerated ML Agent wrapper for SyntheticMortalityAgent.

This file was generated by the CSV Builder Script from synthetic_clinical_dataset.csv.
"""

from pathlib import Path
from typing import Any

from services.ml_mcp_server.models._agent_factory import AgentConfig, DynamicMLAgent

# --- 1. Paths & Configuration ---
_ARTIFACT_PATH = Path(__file__).parent.parent / "artifacts" / "synthetic_mortality_xgb_dynamic.joblib"

_SYNTHETICMORTALITYAGENT_CONFIG = AgentConfig(
    agent_name="synthetic_mortality",
    description="Automated ensemble classifier generated from local data (synthetic_clinical_dataset.csv).",
    version="1.0.0-auto",
    artifact_path=_ARTIFACT_PATH,
    feature_names=['patient_id', 'age', 'bmi', 'systolic_bp', 'diastolic_bp', 'glucose', 'cholesterol', 'creatinine', 'diabetes', 'hypertension', 'readmission_30d', 'gender_Male', 'gender_Other', 'diagnosis_Normal', 'diagnosis_Pneumonia', 'diagnosis_Sepsis'],
    target_classes=['0', '1'],
    trained_on_desc="Local Data via Automated Builder",
    n_splits=5
)

# --- 2. MCP Server Agent Class ---
class SyntheticMortalityAgent(DynamicMLAgent):
    """Dynamic binary classifier for synthetic_mortality."""

    def __init__(self) -> None:
        super().__init__(_SYNTHETICMORTALITYAGENT_CONFIG)

    def sample_inputs(self) -> dict[str, Any]:
        """A representative sample case extracted during the build process."""
        return {
        "patient_id": 1001.0,
        "age": 63.0,
        "bmi": 24.1,
        "systolic_bp": 131.0,
        "diastolic_bp": 81.0,
        "glucose": 136.2,
        "cholesterol": 210.3,
        "creatinine": 1.04,
        "diabetes": 0.0,
        "hypertension": 0.0,
        "readmission_30d": 0.0,
        "gender_Male": 1.0,
        "gender_Other": 0.0,
        "diagnosis_Normal": 0.0,
        "diagnosis_Pneumonia": 0.0,
        "diagnosis_Sepsis": 1.0
        }
