"""Autogenerated ML Agent wrapper for Type2DiabetesAgent.

This file was generated by the CSV Builder Script from type2_diabetes_dataset.csv.
"""

from pathlib import Path
from typing import Any

from services.ml_mcp_server.models._agent_factory import AgentConfig, DynamicMLAgent

# --- 1. Paths & Configuration ---
_ARTIFACT_PATH = Path(__file__).parent.parent / "artifacts" / "type2_diabetes_xgb_dynamic.joblib"

_TYPE2DIABETESAGENT_CONFIG = AgentConfig(
    agent_name="type2_diabetes",
    description="Automated ensemble classifier generated from local data (type2_diabetes_dataset.csv).",
    version="1.0.0-auto",
    artifact_path=_ARTIFACT_PATH,
    feature_names=['pregnancies', 'age', 'bmi', 'systolic_bp', 'diastolic_bp', 'diabetes_pedigree_function', 'insulin', 'skin_thicknessmm', 'glucose'],
    target_classes=['0', '1'],
    trained_on_desc="Local Data via Automated Builder",
    n_splits=5
)

# --- 2. MCP Server Agent Class ---
class Type2DiabetesAgent(DynamicMLAgent):
    """Dynamic binary classifier for type2_diabetes."""

    def __init__(self) -> None:
        super().__init__(_TYPE2DIABETESAGENT_CONFIG)

    def sample_inputs(self) -> dict[str, Any]:
        """A representative sample case extracted during the build process."""
        return {
        "pregnancies": 3.0,
        "age": 50.0,
        "bmi": 22.26376185,
        "systolic_bp": 140.0,
        "diastolic_bp": 90.0,
        "diabetes_pedigree_function": 0.0,
        "insulin": 0.0,
        "skin_thicknessmm": 317.5,
        "glucose": 146.0
        }
