"""Medical expert agent.

The production path calls the configured `MEDICAL_EXPERT_*` LLM provider and
returns a schema-conformant `MedicalExpertResponse`. A deterministic stub is
kept for unit tests and for local runs where no expert provider is configured.
"""

import json
import os
import re
from pathlib import Path
from typing import TYPE_CHECKING, Any, Protocol

from packages.schemas.retrieval import Citation, MedicalExpertResponse, RetrievedDocument

if TYPE_CHECKING:
    from beeai_framework.backend.chat import ChatModel

_SYSTEM_PROMPT_PATH = Path(__file__).parent / "system_prompt.md"

_STUB_DOC = RetrievedDocument(
    title="WHO clinical guideline (stub)",
    snippet=(
        "Stub citation used during early development. The orchestrator's "
        "downstream consumers can rely on the same shape they will see when "
        "the real medical_expert sub-agent is wired up."
    ),
    source_url="https://stub.example.org/who-guideline",
    retrieval_source="local_kb",
)

_EXPERT_AGENT_DOC = RetrievedDocument(
    title="MARGE medical expert agent note",
    snippet=(
        "This consultation was generated by the configured medical expert LLM. "
        "External retrieval-backed citations are not wired in this slice."
    ),
    source_url=None,
    retrieval_source="local_kb",
)

_STUB_REASONING = (
    "Based on the supplied findings (stub response): the patient's profile "
    "warrants further targeted screening. Clinical judgement should "
    "incorporate the ML findings, the patient's history, and standard "
    "guideline-driven thresholds. This is a stub response; replace with the "
    "real medical_expert sub-agent before any clinical use."
)


class MedicalExpert(Protocol):
    def consult(self, question: str, findings: dict[str, Any]) -> Any:
        """Return or await a MedicalExpertResponse."""


class StubMedicalExpert:
    """Returns a fixed MedicalExpertResponse without invoking any LLM."""

    def consult(self, question: str, findings: dict[str, Any]) -> MedicalExpertResponse:
        return MedicalExpertResponse(
            reasoning=_STUB_REASONING,
            citations=[Citation(document=_STUB_DOC, supporting_quote=None)],
        )


class MedicalExpertAgent:
    """LLM-backed medical expert used by the orchestrator's expert tool."""

    def __init__(self, llm: "ChatModel", system_prompt: str | None = None) -> None:
        self._llm = llm
        self._system_prompt = system_prompt or _SYSTEM_PROMPT_PATH.read_text()

    async def consult(self, question: str, findings: dict[str, Any]) -> MedicalExpertResponse:
        from beeai_framework.backend.message import SystemMessage, UserMessage

        payload = {
            "question": question,
            "findings": findings,
        }
        user_prompt = (
            "Review this orchestrator consultation payload and return only JSON.\n\n"
            f"{json.dumps(payload, ensure_ascii=False, default=str)}"
        )
        result = await self._llm.run(
            [SystemMessage(self._system_prompt), UserMessage(user_prompt)]
        )
        raw = result.get_text_content() if hasattr(result, "get_text_content") else str(result)
        return self._parse_response(raw)

    def _parse_response(self, raw: str) -> MedicalExpertResponse:
        try:
            data = _extract_json_object(raw)
        except ValueError:
            data = {
                "reasoning": raw.strip(),
                "abstained": False,
                "abstain_reason": None,
            }

        reasoning = str(data.get("reasoning") or "").strip()
        if not reasoning:
            reasoning = (
                "The medical expert could not provide a detailed interpretation "
                "from the available consultation payload."
            )

        abstained = bool(data.get("abstained", False))
        abstain_reason = data.get("abstain_reason")
        if abstain_reason is not None:
            abstain_reason = str(abstain_reason)

        citations = _parse_citations(data.get("citations"))
        if not citations and not abstained:
            citations = [Citation(document=_EXPERT_AGENT_DOC, supporting_quote=None)]

        return MedicalExpertResponse(
            reasoning=reasoning,
            citations=citations,
            abstained=abstained,
            abstain_reason=abstain_reason,
        )


def build_medical_expert_agent() -> MedicalExpert:
    """Build the configured expert agent, or a stub when no expert is configured."""
    if _env_truthy("MARGE_USE_STUB_EXPERT") or not _expert_env_configured():
        return StubMedicalExpert()

    from packages.llm_provider.client import build_chat_model_for_role
    from packages.llm_provider.settings import Role

    return MedicalExpertAgent(build_chat_model_for_role(Role.MEDICAL_EXPERT))


def _extract_json_object(text: str) -> dict[str, Any]:
    stripped = text.strip()
    fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", stripped, flags=re.DOTALL)
    if fenced:
        stripped = fenced.group(1)
    else:
        start = stripped.find("{")
        end = stripped.rfind("}")
        if start == -1 or end == -1 or end <= start:
            raise ValueError("No JSON object found in expert response.")
        stripped = stripped[start : end + 1]

    parsed = json.loads(stripped)
    if not isinstance(parsed, dict):
        raise ValueError("Expert response JSON must be an object.")
    return parsed


def _parse_citations(value: Any) -> list[Citation]:
    if not isinstance(value, list):
        return []

    citations: list[Citation] = []
    for item in value:
        if not isinstance(item, dict):
            continue

        title = str(item.get("title") or "Medical source")
        snippet = str(item.get("snippet") or item.get("supporting_quote") or "")
        source_url = item.get("source_url")
        supporting_quote = item.get("supporting_quote")
        document = RetrievedDocument(
            title=title,
            snippet=snippet or title,
            source_url=str(source_url) if source_url else None,
            retrieval_source="web" if source_url else "local_kb",
        )
        citations.append(
            Citation(
                document=document,
                supporting_quote=str(supporting_quote) if supporting_quote else None,
            )
        )
    return citations


def _expert_env_configured() -> bool:
    return bool(os.getenv("MEDICAL_EXPERT_PRIMARY") or os.getenv("LLM_PROVIDER"))


def _env_truthy(name: str) -> bool:
    return os.getenv(name, "").strip().lower() in {"1", "true", "yes", "on"}
